import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import ImagePeopleHome from "../components/ImagePeopleHome";
import GlobalStyle from "../styles/globals";
import { MaxContainerHome } from "../styles/style";
import { sanityClient } from "../sanity";
import { Post } from "../typings";

interface Props {
	posts: [Post];
}
const Home = ({ posts }: Props) => {

	console.log(posts)
	return (
		<>
			<GlobalStyle />

			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<MaxContainerHome>
				<div className="container-text-home">
					<h1>
						O blog de{" "}
						<span style={{ color: "#FF3651" }}>Tech</span> com sua cara!
					</h1>
					<p>
						Aqui é o ambiente onde você, estudante entusiasta, aluno, professor, ou curioso da tecnologia pode ler sobre as tecnologias e metodologias mais atuais do mercado!
					</p>

					<Link href="#">Começar a ler agora</Link>
				</div>
				<ImagePeopleHome />
			</MaxContainerHome>

			{/* POSTS */}
		</>
	);
};

export default Home;

export const getServerSideProps = async () => {
	const query = `
		*[_type == "post"]{
			_id,
			title,
			author -> {
				name, image
			},
			description,
			mainImage,
			slug
		}
	`;

	const posts = await sanityClient.fetch(query);

	return {
		props: {
			posts,
		},
	};
};
